# Generated by Django 3.2.3 on 2021-05-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_files', '0003_alter_post_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(upload_to='files'),
        ),
    ]
