# Generated by Django 3.2.3 on 2021-05-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_files', '0005_auto_20210526_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Nombre_del_archivo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted_by',
            new_name='compartido_por',
        ),
    ]
