# Generated by Django 3.2.3 on 2021-05-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_files', '0006_auto_20210526_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Nombre_del_archivo',
            new_name='nombre_del_archivo',
        ),
    ]
