# Generated by Django 3.2.3 on 2021-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_files', '0007_rename_nombre_del_archivo_post_nombre_del_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
