# Generated by Django 3.2.3 on 2021-05-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_files', '0009_alter_post_posted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='archivo',
        ),
    ]
